server:
  port: 10001

web:
  base-path: '/usr1/local',
  upload-path: '/hutu-order/web/upload'

# 业务配置
business:
  # 堂食订单前缀
  prefix-eat-in: 'H'
  # 外带订单前缀
  prefix-take-out: 'T'
  # 订单超时时间(秒)
  order-expire: 300
  # 每日订单号长度
  order-length: 3
  # 订单超时检查类型
  check-type: delayedQueue

spring:
  redis:
    host: localhost
    password:
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        time-out: 3000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: hutu-order
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/hutu-order?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-test-query: select 1
  sa-token:
    # token 名称（同时也是 cookie 名称）
    token-name: Token
    # token 有效期（单位：秒） 默认30天，-1 代表永久有效
    timeout: 2592000
    # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
    active-timeout: -1
    # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
    is-share: true
    # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
    token-style: uuid
    # 是否输出操作日志
    is-log: true

interceptor:
  authorize: false

logging:
  config: classpath:logback-dev.xml
  level:
    org.nott.web.mapper: debug

# 支付宝支付信息
alipay:
  appId:
  privateKey:
  publicKey:
  signType: RSA2
  notifyUrl:

# 微信小程序信息
wechat:
  app:
    appId:
    appSecret:

# 微信支付信息
weixinpay:
  mchId:
  appId:
  apiV3Key:
  notifyUrl:
  privateKeyPath:
  merchantSerialNumber:

# 内部支付包名
payment:
  package:
    name: org.nott.payment

swagger2:
  group-name: "糊涂点餐-用户端"